name: Run Chapter 3 & Commit Plots

on:
  push:
    branches:
      - main
    # Ignore commits to PNG files to prevent workflow loops
    paths-ignore:
      - 'Chapter3/3_1_1/*.png'
      - 'Chapter3/3_1_2/*.png'
      - 'Chapter3/3_1_3/*.png'
      - 'Chapter3/3_1_4/*.png'
      #  TODO: Add the neumann example for 3_1_5
      - 'Chapter3/3_1_6/*.png'
      - 'Chapter3/3_1_7/*.png'
      - 'Chapter3/3_1_8/*.png'
      - 'Chapter3/3_1_9/*.png'
      - 'Chapter3/3_2_1/*.png'
      - 'Chapter3/3_2_2/*.png'
      - 'Chapter3/3_2_3/*.png'
      - 'Chapter3/3_2_4/*.png'
      - 'Chapter3/3_2_5/*.png'
      - 'Chapter3/3_2_6/*.png'

  schedule:
    # Runs every Monday at 00:00 UTC
    - cron: "0 0 * * 1"
  workflow_dispatch:  # allow manual trigger

jobs:
  run-chapter3:
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v4

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Pull Docker image
    - name: Pull prebuilt Docker image
      run: docker pull zoeleibowitz/petsc_devito_image:latest

    # Run 3_1_1 - serial
    - name: Run 3_1_1 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_1 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 1d_poisson.py

    # Run 3_1_2 - serial
    - name: Run 3_1_2 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_2 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 2d_poisson.py

    # Run 3_1_3 - serial
    - name: Run 3_1_3 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_3 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 3d_poisson.py

    # Run 3_1_4 - serial
    - name: Run 3_1_4 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_4 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 2d_laplace_sine.py

    # Don't run 3_1_5 yet -> need to fix nullspace treatment

    # Run 3_1_6 - serial
    - name: Run 3_1_6 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_6 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 2d_modified_helmholtz.py

    # Run 3_1_7 - serial
    - name: Run 3_1_7 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_7 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 modified_stencil_4th_order.py

    # Run 3_1_8 - serial
    - name: Run 3_1_8 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_8 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 poisson_collatz.py

    # Run 3_1_9 - serial
    - name: Run 3_1_9 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_9 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 rectangle2d.py

    # Run 3_2_1 - serial
    - name: Run all .py scripts in 3_2_1 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_2_1 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          bash -c 'for f in *.py; do echo "Running $f..."; python3 "$f"; done'

    # Run 3_2_2 - serial
    - name: Run 3_2_2 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_2_2 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 3_2_2_ftcs.py

    # Run 3_2_3 - serial
    - name: Run 3_2_3 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_2_3 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 3_2_3.py

    # Run 3_2_4 - serial
    - name: Run 3_2_4 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_2_4 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 3_2_4.py

    # Run 3_2_5 - serial
    - name: Run 3_2_5 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_2_5 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 wave_2d.py

    # Run 3_2_6 - serial
    - name: Run 3_2_6 - serial
      run: |
        docker run --rm -t \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_2_6 \
          -u $(id -u):$(id -g) \
          zoeleibowitz/petsc_devito_image:latest \
          python3 wave_3d.py

    # Configure Git for commits
    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit plots and create PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="update-ch3-$(date +%s)"
        git checkout -b $BRANCH_NAME
        git add Chapter3/3_1_1/*.png
        git add Chapter3/3_1_2/*.png
        git add Chapter3/3_1_3/*.png
        git add Chapter3/3_1_4/*.png
    
        git add Chapter3/3_1_6/*.png
        git add Chapter3/3_1_7/*.png
        git add Chapter3/3_1_8/*.png
        git add Chapter3/3_1_9/*.png
        git add Chapter3/3_2_1/*.png
        git add Chapter3/3_2_2/*.png
        git add Chapter3/3_2_3/*.png
        git add Chapter3/3_2_4/*.png
        git add Chapter3/3_2_5/*.png
        git add Chapter3/3_2_6/*.png

        git commit -m "Update plots for Chapter3 from workflow" || echo "No changes to commit"
        git push --set-upstream https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $BRANCH_NAME
        gh auth setup-git
        gh pr create \
          --title "Update plots for Chapter3" \
          --body "Generated automatically by workflow." \
          --base main \
          --head $BRANCH_NAME
