name: Run Chapter 3 with MPI
# NOTE: purely checking for correctness .. using oversubscribe

on:
  push:
    branches:
      - main

  schedule:
    # Runs every Monday at 00:00 UTC
    - cron: "0 0 * * 1"
  workflow_dispatch:  # allow manual trigger

env:
  DOCKER_IMAGE: devitocodes/devito-petsc:latest
  DEVITO_MPI: "1"
  MPI_N: 4

jobs:
  run-chapter3:
    name: Run Chapter 3 (MPI n=4)
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v4

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Pull Docker image
    - name: Pull prebuilt Docker image
      run: docker pull $DOCKER_IMAGE

    ################################## 311 ##################################
    - name: Run 3_1_1 - parallel
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_1 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 1d_poisson_mpi.py

    - name: Run 3_1_1 - parallel - constrain bcs
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_1 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 1d_poisson_constrain_mpi.py

    ################################## 312 ##################################

    - name: Run 3_1_2 - parallel
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_2 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 2d_poisson_mpi.py

    - name: Run 3_1_2 - parallel - constrain bcs
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_2 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 2d_poisson_constrain_mpi.py

    ################################## 313 ##################################
    # TODO: add the constrain bc test for 313

    - name: Run 3_1_3 - parallel
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_3 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 3d_poisson_mpi.py

    ################################## 314 ##################################
    - name: Run 3_1_4 - parallel
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_4 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 2d_laplace_sine_mpi.py

    - name: Run 3_1_4 - parallel - constrain bcs
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_4 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 2d_laplace_sine_constrain_mpi.py

    # TODO: insert 315 parallel tests

    ################################## 316 ##################################

    - name: Run 3_1_6 - parallel
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_6 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 2d_modified_helmholtz_mpi.py

    # ################################## 317 ##################################

    - name: Run 3_1_7 - parallel
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_7 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 modified_stencil_4th_order_mpi.py

    - name: Run 3_1_7 - parallel - constrain bcs
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_7 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 modified_stencil_4th_order_constrain_mpi.py

    ################################# 318 ##################################

    - name: Run 3_1_8 - parallel
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_8 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 poisson_collatz_mpi.py

    - name: Run 3_1_8 - parallel - constrain bcs
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_8 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 poisson_collatz_constrain_mpi.py

    ################################## 319 ##################################

    - name: Run 3_1_9 - parallel
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_9 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 rectangle2d_mpi.py

    - name: Run 3_1_9 - parallel - constrain bcs
      run: |
        docker run --rm -t \
          -e DEVITO_MPI \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Chapter3/3_1_9 \
          -u $(id -u):$(id -g) \
          $DOCKER_IMAGE \
          mpiexec --oversubscribe -n $MPI_N python3 rectangle2d_constrain_mpi.py

    # Configure Git for commits
    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit plots and create PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="update-ch3-$(date +%s)"
        git checkout -b $BRANCH_NAME

        git add Chapter3/3_1_1/*.png
        git add Chapter3/3_1_2/*.png
        git add Chapter3/3_1_3/*.png
        git add Chapter3/3_1_4/*.png

        git add Chapter3/3_1_6/*.png
        git add Chapter3/3_1_7/*.png
        git add Chapter3/3_1_8/*.png
        git add Chapter3/3_1_9/*.png

        if git diff --cached --quiet; then
          echo "No changes to commit, skipping PR."
          exit 0
        fi

        git commit -m "Update plots for Chapter3 from workflow"
        git push --set-upstream https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $BRANCH_NAME
        gh auth setup-git
        gh pr create \
          --title "Update plots for Chapter3" \
          --body "Generated automatically by workflow." \
          --base main \
          --head $BRANCH_NAME
